django_test_platform/django_test_platform/urls.py
from django.contrib import admin
from django.urls import include,path
from user_app import views

#路由匹配

urlpatterns = [
    path('admin/', admin.site.urls),

    path('example/', include('example.urls')),

    #用户应用
    path('', views.index),
    path('index/', views.index),
    path('accounts/login/',views.index),
    path('logout/', views.logout),

    #项目管理
    path('project/', include('project_app.urls')),

    #模块管理
    path('module/', include('module_app.urls')),

    #模块管理
    path('testcase/', include('testcase_app.urls')),

    #任务管理
    path('testtask/', include('testtask_app.urls')),

]

django_test_platform/example/urls.py
from django.urls import path

from . import views

app_name = 'example'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django_test_platform/example/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    description = models.CharField(max_length=200,default='')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django_test_platform/example/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'example/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'example/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'example/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'example/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('example:results', args=(question.id,)))

django_test_platform/example/templates/example/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'example:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <label for="choice{{ forloop.counter }}">{{ choice.description }}</label><br>
{% endfor %}<br>
<input type="submit" value="Vote">
</form>

django_test_platform/example/templates/example/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'example/style.css' %}">

<h1 style="color:red">投票列表</h1>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'example:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No example are available.</p>
{% endif %}

django_test_platform/example/templates/example/results.html
<h1>{{ question.question_text }}</h1>

<h1 style="color:red">投票结果</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} 票</li>
{% endfor %}
</ul>

<a href="{% url 'example:detail' question.id %}">Vote again?</a>